project:
  type: website

website:
  title: "miserable uncertainty"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://scicomm.xyz/@jarek
format:
  html:
    theme: simplex
    css: styles.css

editor: source

